AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select key pair
  EnvironmentName:
    Description: Select the env
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
Mappings:
#First Map
  MyRegionMap:
    #First level key
    us-east-2:
      #Second level key
      HVM64: ami-0443305dabd4be2bc
    us-west-1:
      HVM64: ami-04b6c97b14c54de18
#Second Map
  MyEnvironmentMap:
  #First level key
    dev:
      #Second level key
      instanceType: t2.micro
    prod:
      instanceType: t2.small


Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !FindInMap 
        - MyEnvironmentMap
        - !Ref EnvironmentName
        - instanceType
      KeyName: !Ref MyKeyName