AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select key pair
Mappings:
  MyRegionMap:
    #Top level key
    us-east-2:
      #Second level key
      HVM64: ami-0443305dabd4be2bc
    us-west-1:
      HVM64: ami-04b6c97b14c54de18
Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
