AWSTemplateFormatVersion: 2010-09-09
Description: KeyName Parameter demo

Parameters:
  #LogicalID
  MyKeyName:
    Description: Select the KeyName from list
    Type: AWS::EC2::KeyPair::KeyName


Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0443305dabd4be2bc
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default        
        - !Ref SSHSecurityGroup 
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: my new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
