#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html
AWSTemplateFormatVersion: 2010-09-09
Description: VPC STACK NESTED INTO ROOT STACK, WHERE EC2 INSTANCE CAN BE LAUNCHED IN

Parameters:
  MyKeyName: 
    Type: AWS::EC2::KeyPair::KeyName
  VpcBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR Tange
  cfnsubnetBlock01: 
    Type: String
    Default: 10.0.1.0/24
    Description: CidrBlock for Subnet within the VPC

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://cfn-nested-ts01.s3.us-east-2.amazonaws.com/nested-stacks/13-01-NestedStack-VPC.yaml
      Parameters:
        VpcBlock: !Ref VpcBlock
        cfnsubnetBlock01: !Ref cfnsubnetBlock01
      TimeoutInMinutes: 5
      
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-00dfe2c7ce89a450b
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"  
          SubnetId: !GetAtt VPCStack.Outputs.cfnsubnetId

      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update
          sudo yum -y erase java-1.7.0-openjdk.x86_64
          sudo yum -y install java-1.8.0-openjdk.x86_64
          sudo yum -y install java-1.8.0-openjdk-devel
          sudo yum -y install tomcat8
          service tomcat8 start
          mkdir /usr/share/tomcat8/webapps/ROOT
          touch /usr/share/tomcat8/webapps/ROOT/index.html
          echo "Cloud Formation Tomcat8" > /usr/share/tomcat8/webapps/ROOT/index.html

Outputs:

  AppURL: 
    Description: App URL
    Value: !Sub 'http://${MyVMInstance.PublicDnsName}:8080/index.html'